### PR TITLE
npdm: Update debug flag printout

### PR DESCRIPTION
**Pull request by borntohonk**
This probably needs an if condition block for when there's less than 3 debug flags to print only allow_debug and force_debug, but at least this way it's able to properly print the debug flags of something built with latest switch-tools (19.0.0)

### CODE REVIEW

**Comment by masagrator** [comment]
> This probably needs an if condition block for when there's less than 3 debug flags to print only allow_debug and force_debug

This is actually wrong. You cannot discern between new npdm with force_debug_prod set to true and old npdm with force_debug set to true. This is breaking change and you can't do anything about that.

That's why all homebrew that must have force_debug set to true must be repacked with new npdm.

**Comment by borntohonk** [comment]
> > This probably needs an if condition block for when there's less than 3 debug flags to print only allow_debug and force_debug
> 
> This is actually wrong. You cannot discern between new npdm with force_debug_prod set to true and old npdm with force_debug set to true. This is breaking change and you can't do anything about that.

```
        Allow Debug:                YES
        Force Debug Prod:           NO
        Force Debug:                YES
```

oh well, too bad I guess "old" .npdms getting read will say force_debug prod_keys instead of force_debug yes

**Comment by SciresM** [comment]
> > This probably needs an if condition block for when there's less than 3 debug flags to print only allow_debug and force_debug
> 
> This is actually wrong. You cannot discern between new npdm with force_debug_prod set to true and old npdm with force_debug set to true. This is breaking change and you can't do anything about that.
> 
> That's why all homebrew that must have force_debug set to true must be repacked with new npdm.

wdym? SDK version is present in NCA header, for non-homebrew this distinguishes

**Comment by masagrator** [comment]
Afaik all games have allow_debug set to true, so imo it's pointless to do this check.

**Pull request closed without merging**
