### PR TITLE
Add and organize readme

### PR DESCRIPTION
**Pull request by Pysis868**
https://github.com/SciresM/hactool/issues/118#issuecomment-1599750947
https://github.com/SciresM/hactool/issues/79#issuecomment-1106574369

### CODE REVIEW

**Comment by SciresM** [comment]
This is a troll PR.

**Comment by Pysis868** [comment]
How is that?

**Comment by SciresM** [comment]
This:

* Changes the formatting of output for no reason.
* Adds `This is required.` note to a field that...is not required.
* Adds `  Also works using Cygwin.` which is both irrelevant and has a formatting inconsistency (one space should be used, not two).
* Adds an unnecessary note about disablekeywarns to the README despite disablekeywarns literally being in the help/usage.

If it's not a troll PR, it's severely misguided, and *bizarre* to make without e.g. talking to me on discord first.

**Comment by Pysis868** [comment]
- There is a fine reason, as I was just using the updated organization to scan sections more easily.
- It must default to nca mode when I was operating on other file types but kept receiving header/checksum errors.  This is also referenced in 1 of the issues that I mentioned.
- Totally relevant as a similar supportive technology recommendation used for Windows like MinGW.  Adding the note, especially brief, should hardly trouble, like most of this PR.
- Added as well like other issues have mentioned, the default being to display what users could misinterpret to cause errors, and to the existing key section in the readme as another brief note.

You have no contributing guidelines until the slight mention in this specific place.  I am offering these changes, certainly with no initial harsh tone, and would ask that it be received without one too, especially concerning how simple the request is.

We can work here, or on Discord, but as I know people do not appreciate unsolicited DMs on that, and many other platforms, it is apparently impossible to avoid troubling situations just based on assumptions, which is why I simply posted this request here where it is common to do so, and there are also collaborative functions, not just for notification.

**Comment by SciresM** [comment]
Well, to be frank:

* I am not interested in changing the formatting.
* Yes, it defaults to processing NCAs.
* I do not use cygwin and don't recommend it, as I think it's worse, and wouldn't want it suggested in a README.
* I do not want such a note in the README.

This tone isn't intended to be harsh -- it's meant to be straightforward and honest. I genuinely took the PR to be from a troll. You're welcome to reach out to me at `SciresM` on discord! I recommend doing so before making PRs.

**Comment by Pysis868** [comment]
At least add that Discord note to the readme or a contributing file for others and even me if I forget.

**Comment by SciresM** [comment]
I prefer not to have a CONTRIBUTING.md or similar. Contributors are *rare* and this is a niche space (yours is, I note, the only PR in over two years) -- and hactool is almost deprecated, anyway. I would rather just tell people to reach out on discord as they may.

I might have not taken your PR as being from a troll if you had included...literally any full English sentences explaining rationale instead of just linking to issues, which was also terse.

**Comment by Pysis868** [comment]
Just trying to let the title, commit messages, code, and responses in issues speak for themselves, especially with a small and non-functional change set.  Better than causing others to parse a lot of communication unnecessarily, and that can always be continued.

If you're referring to hac2l, then I see it now, but can't even get it building yet, also as there is no release package posted.

**Comment by SciresM** [comment]
I fundamentally disagree with you about "letting the title, commit messages, code, etc" speak for themselves. If a change set is small and non-functional, it shouldn't be made without discussion beforehand, and it should have a full English justification.

This is presumably just a culture difference. And, yes, hactool is not receiving further technical updates. `hac2l` isn't complete, though, and has not had any releases. It is the only tool which supports some newer formats, though.

**Pull request closed without merging**
